DAILY_STUDY_REMINDER = "DAILY_STUDY_REMINDER"
DAILY_STUDY_REMINDER_TYPE = "daily_study_reminder"
SHOP_UNLOCK_NOTIFICATION = "SHOP_UNLOCK"
SHOP_UNLOCK_NOTIFICATION_TYPE = "shop_unlock"
USER_NOTIFICATION_STORED = "stored"

OUTBOX_PENDING = "pending"
OUTBOX_PROCESSING = "processing"
OUTBOX_SENT = "sent"
OUTBOX_PARTIAL = "partial"
OUTBOX_FAILED = "failed"
OUTBOX_SKIPPED = "skipped"
OUTBOX_CANCELLED = "cancelled"

DELIVERY_PENDING = "pending"
DELIVERY_SENT = "sent"
DELIVERY_FAILED = "failed"
DELIVERY_PERMANENT_FAILURE = "permanent_failure"
DELIVERY_TRANSIENT_FAILURE = "transient_failure"
DELIVERY_SKIPPED = "skipped"

REMINDER_TITLE = "\u0110\u1ebfn gi\u1edd h\u1ecdc r\u1ed3i! \U0001f4da"
REMINDER_BODY = "Buddy \u0111ang ch\u1edd b\u1ea1n. B\u1eaft \u0111\u1ea7u m\u1ed9t phi\u00ean t\u1eadp trung ng\u1eafn nh\u00e9!"
REMINDER_ICON = "/buddies/miu.jpg"

BACKOFF_SECONDS = [30, 120, 600, 1800]

INSTALLATION_ID_MIN_LENGTH = 8
INSTALLATION_ID_MAX_LENGTH = 128
ENDPOINT_MIN_LENGTH = 16
ENDPOINT_MAX_LENGTH = 4096
P256DH_MIN_LENGTH = 16
P256DH_MAX_LENGTH = 512
AUTH_MIN_LENGTH = 8
AUTH_MAX_LENGTH = 256
